name: python_for_data_science
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - altair=4.1.0=py_1
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - asn1crypto=1.4.0=py_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - bokeh=2.2.3=py37_0
  - branca=0.3.1=py_0
  - brotli-python=1.0.9=py37heb0550a_2
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.12.8=h06a4308_0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.0=py37h2e261b9_0
  - cfitsio=3.470=hb7c8383_2
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.1.2=py_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=py37h06a4308_0
  - colorcet=2.0.2=py_0
  - cryptography=3.3.1=py37h3c74f83_0
  - curl=7.67.0=hbc83047_0
  - cycler=0.10.0=py37_0
  - dash=1.18.1=pyhd3eb1b0_0
  - dash-core-components=1.3.1=py_0
  - dash-html-components=1.0.1=py_0
  - dash-renderer=1.1.2=py_0
  - dash-table=4.4.1=py_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - descartes=1.1.0=py_4
  - entrypoints=0.3=py37_0
  - expat=2.2.10=he6710b0_2
  - fiona=1.8.13.post1=py37hc820daa_0
  - flask=1.1.2=py_0
  - flask-compress=1.8.0=pyhd3eb1b0_0
  - folium=0.10.0=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - freexl=1.0.6=h27cfd23_0
  - future=0.18.2=py37_1
  - gdal=3.0.2=py37hbb2a789_0
  - geopandas=0.8.1=py_0
  - geos=3.8.0=he6710b0_0
  - geotiff=1.5.1=h21e8280_1
  - giflib=5.1.4=h14c3975_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - holoviews=1.14.0=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.19.0=py37hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.5.1=py_1
  - itsdangerous=1.1.0=py37_0
  - jedi=0.17.2=py37h06a4308_1
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.0=py37h06a4308_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - kealib=1.4.7=hd0c454d_6
  - kiwisolver=1.3.0=py37h2531618_0
  - krb5=1.16.4=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.67.0=h20c2e04_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgdal=3.0.2=h27ab9cc_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h11d0813_2
  - libpng=1.6.37=hbc83047_0
  - libpq=11.2=h20c2e04_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=he6710b0_0
  - libspatialite=4.3.0a=h793db0d_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.8.1.2=h14c3975_0
  - markdown=3.3.3=py37h06a4308_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37h817c723_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - munch=2.5.0=py_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.1.4=py37_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1i=h27cfd23_0
  - packaging=20.7=pyhd3eb1b0_0
  - pandas=1.1.3=py37he6710b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - panel=0.10.2=pyhd3eb1b0_0
  - param=1.10.0=pyhd3eb1b0_0
  - parso=0.7.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.0.1=py37he98fc37_0
  - pip=20.3.1=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - plotly=4.14.1=pyhd3eb1b0_0
  - poppler=0.65.0=h581218d_1
  - poppler-data=0.4.10=h06a4308_0
  - postgresql=11.2=h20c2e04_0
  - proj=6.2.1=haa6030c_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.6.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pyct=0.4.8=py37_0
  - pygments=2.7.3=pyhd3eb1b0_0
  - pyopenssl=20.0.0=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyproj=2.6.1.post1=py37hd003209_1
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.7=h191fe78_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.4=pyhd3eb1b0_0
  - pyviz_comms=0.7.6=py_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - pyzmq=20.0.0=py37h2531618_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - requests=2.25.0=pyhd3eb1b0_0
  - retrying=1.3.3=py37_2
  - rtree=0.9.4=py37_1
  - scipy=1.5.2=py37h0b6359f_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=51.0.0=py37h06a4308_2
  - shapely=1.7.1=py37h98ec03d_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py37h06a4308_0
  - soupsieve=2.0.1=py_0
  - sqlalchemy=1.3.20=py37he8ac12f_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.12.1=py37h27cfd23_0
  - tbb=2018.0.5=h6bb024c_0
  - terminado=0.9.1=py37_0
  - testpath=0.4.4=py_0
  - tiledb=1.6.3=h1fb8f14_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.54.1=pyhd3eb1b0_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.25.11=py_0
  - vega=3.4.0=py37hc8dfbb8_1
  - vincent=0.4.4=py_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=py_0
  - wheel=0.36.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py37_0
  - xarray=0.16.2=pyhd3eb1b0_0
  - xerces-c=3.2.3=h780794e_0
  - xlrd=1.2.0=py37_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/gjb/miniconda3/envs/python_for_data_science
